name = "gtabler"
version = "0.1.0"

description = "A customizable library for printing tables with colors and styles in Gleam."
licences = ["MIT"]
repository = { type = "github", user = "eAntillon", repo = "gleam_table_printer" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
